# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    - id: no-commit-to-branch
- repo: local
  hooks:
  - id: validate_pre-commit
    name: Checks pre-commit against /etc/defaults/pre-commit-config.yaml
    entry: /usr/bin/diff
    args:
    - /etc/defaults/pre-commit-config.yaml
    - ./.pre-commit-config.yaml
    files: ./.pre-commit-config.yaml
    always_run: true
    language: script
