# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: flake8
  - id: mixed-line-ending
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.1  # Use the sha / tag you want to point at
  hooks:
  - id: pylint
- repo: https://github.com/detailyang/pre-commit-shell.git
  rev: 1.0.4
  hooks:
  - id: shell-lint
    types: ["shell"]
