#!/bin/bash
#################################################################
#	Name: 	install				#
#	Description: Installation des fichiers de configuration	#
#################################################################

echo "Maj des fichiers de config"
configdir="$HOME/.myconfig"

ln -sf $configdir/bash/bashrc 		$HOME/.bashrc
ln -sf $configdir/bash/bash_aliases 	$HOME/.bash_aliases
ln -sf $configdir/bash/bash_completion	$HOME/.bash_completion
ln -sf $configdir/bash/bash_completion.d  $HOME/.bash_completion.d
ln -sf $configdir/bash/profile 		$HOME/.profile

ln -sf $configdir/screen/screenrc 	$HOME/.screenrc

ln -sf $configdir/vim/vimrc 	$HOME/.vimrc
