# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000
HISTTIMEFORMAT="%d/%m/%Y %H:%M:%S "


unset TMOUT

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


function build_my_prompt {
    PROMPT_DIRTRIM=3
    local _user_at_host='\[\033[01;32m\]\u@\h\[\033[00m\]'
    local _current_dir='\[\033[01;34m\]\w\[\033[00m\]'
    local _git_branch='`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\/`'
    export PS1="${_user_at_host}:${_current_dir}${_git_branch} \$ "
}

export PS1="\$"
case "$TERM" in
    xterm) build_my_prompt;;

esac

# If this is an xterm set the title to user@host:dir
case "$TERM" in
    xterm*|rxvt*)
        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
        ;;
    *)
        ;;
esac

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Extends my bash with functions:
if [ -f ~/.bash_fonctions.d/enabled.sh ]; then
    . ~/.bash_fonctions.d/enabled.sh
fi


if [ -d ~/bin ]; then
    PATH="$HOME/bin:$PATH"
fi

if [ -n "$DESKTOP_SESSION" ]; then
    # Désactive le capslock
    test -x /usr/bin/setxkbmap && /usr/bin/setxkbmap -option ctrl:nocaps

    # Active le verrou numerique
    test -x /usr/bin/numlockx && /usr/bin/numlockx on
fi

# Pythonrc file:
PYTHONSTARTUP=~/.pythonrc

export PYTHONSTARTUP

# Exports pew env to prompt:
if [ -f /usr/local/bin/pew ]; then
    source "$(pew shell_config)"
fi
